### ISSUE TITLE
Now on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [garden-rs/garden#13]
Hi,

FYI, I've packaged `garden` for pkgsrc/NetBSD and merged the package into the main branch, http://mail-index.netbsd.org/pkgsrc-changes/2023/01/22/msg267560.html

This means users will be able to install `garden` from the official repositories using the native package manager, _i.e._ `pkgin install garden`

If users still prefer to build it from source, they can easily do that by
```
cd /usr/pkgsrc/devel/garden
make install
```

Regards

**Comment by davvid** [comment]
Thank you so much, that's really great to hear! I'll leave this issue open as a reminder to to add these instructions to the Installation instructions (`doc/src/installation.md`).

**Comment by 0323pin** [comment]
@davvid If I find the time, I'll make a PR for it ;)

**Comment by davvid** [comment]
Thanks @0323pin ~ I've added a NetBSD section to the [installation instructions](https://davvid.github.io/garden/installation.html#install-on-netbsd) and [mentioned you in the upcoming v0.7.0 release notes](https://davvid.github.io/garden/changelog.html#v070).

Please let me know (or submit a PR) if there are any details you'd like to change.

cheers!

**Comment by 0323pin** [comment]
@davvid Thank you! Looks good to me.
