### ISSUE TITLE
Garden grow doesn't do a full git clone

### ISSUE THREAD

**Issue by mrosm20** [garden-rs/garden#2]
the remotes branch aren't fetched when you perform a garden grow. you can't checkout a branch from the origin.

**Comment by davvid** [comment]
Good point, right now we have `--depth=1` hard-coded in `src/cmds/grow.rs`.

That should be made opt-in via a new `depth: 1` attribute instead.

In the meantime removing the hard-coded `--depth=1` there is a good solution.

**Comment by davvid** [comment]
Thanks for the report. We now create full clones by default.

You can add `depth: 1` to a tree (or template) configuration to enable shallow cloning. It's an integer, so `depth: 42` will create a shallow clone of depth 42.
